
import React from 'react';

interface TranslationOutputProps {
    translation: string;
    modelName?: string;
    isLoading?: boolean;
    onAccept?: () => void;
    onRegenerate?: () => void;
}

export default function TranslationOutput({
    translation,
    modelName = 'Meta Llama 3.3',
    isLoading = false,
    onAccept,
    onRegenerate
}: TranslationOutputProps) {
    if (isLoading) {
        return (
            <div className="translation-output-panel loading">
                <style jsx>{`
                    .translation-output-panel {
                        background: white;
                        border: 1px solid #93a1a1;
                        border-radius: 8px;
                        padding: 24px;
                        min-height: 200px;
                        display: flex;
                        flex-direction: column;
                        align-items: center;
                        justify-content: center;
                    }
                    .spinner {
                        width: 32px;
                        height: 32px;
                        border: 3px solid #eee8d5;
                        border-top-color: #268bd2;
                        border-radius: 50%;
                        animation: spin 1s linear infinite;
                        margin-bottom: 12px;
                    }
                    @keyframes spin { to { transform: rotate(360deg); } }
                    .loading-text { color: #586e75; font-size: 14px; }
                `}</style>
                <div className="spinner" />
                <div className="loading-text">Generating translation with {modelName}...</div>
            </div>
        );
    }

    if (!translation) return null;

    return (
        <div className="translation-output-panel">
            <style jsx>{`
                .translation-output-panel {
                    background: white;
                    border: 1px solid #93a1a1;
                    border-radius: 8px;
                    overflow: hidden;
                    font-family: system-ui, -apple-system, sans-serif;
                }
                .panel-header {
                    background: #eee8d5;
                    padding: 12px 16px;
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    border-bottom: 1px solid #93a1a1;
                }
                .model-badge {
                    font-size: 12px;
                    color: #586e75;
                    display: flex;
                    align-items: center;
                    gap: 6px;
                }
                .model-dot {
                    width: 8px;
                    height: 8px;
                    background: #2aa198;
                    border-radius: 50%;
                }
                .content {
                    padding: 24px;
                    font-size: 16px;
                    line-height: 1.8;
                    color: #073642;
                    white-space: pre-wrap;
                }
                .actions {
                    padding: 16px;
                    background: #fdf6e3;
                    border-top: 1px solid #eee8d5;
                    display: flex;
                    justify-content: flex-end;
                    gap: 12px;
                }
                .btn {
                    padding: 8px 16px;
                    border-radius: 6px;
                    font-size: 14px;
                    font-weight: 500;
                    cursor: pointer;
                    border: none;
                    transition: all 0.2s;
                }
                .btn-secondary {
                    background: white;
                    border: 1px solid #93a1a1;
                    color: #586e75;
                }
                .btn-secondary:hover { background: #eee8d5; }
                .btn-primary {
                    background: #268bd2;
                    color: white;
                }
                .btn-primary:hover { background: #1a6ba8; }
            `}</style>

            <div className="panel-header">
                <div className="model-badge">
                    <div className="model-dot" />
                    Generated by {modelName} (Natural)
                </div>
            </div>

            <div className="content">
                {translation}
            </div>

            <div className="actions">
                <button className="btn btn-secondary" onClick={onRegenerate}>
                    🔄 Regenerate
                </button>
                <button className="btn btn-primary" onClick={onAccept}>
                    ✅ Accept & Save
                </button>
            </div>
        </div>
    );
}
